// Knockout JavaScript library v2.1.0+mbest/smart-binding/beta.6
// (c) Steven Sanderson - http://knockoutjs.com/
// License: MIT (http://www.opensource.org/licenses/mit-license.php)

(function() {var m=!0,p=null,r=!1;(function(x,q,M,s,n){function o(n){throw Error(n);}(function(n){"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?n(module.exports||exports):"function"===typeof define&&define.amd?define(["exports"],n):n(x.ko={})})(function(C){function E(b){function c(c){return function(){var e={templateEngine:a.L.ib};b(c(),e);return e}}return{flags:80,init:function(b,e){return a.c.template.init(b,c(e))},update:function(b,e,f,g,k){return a.c.template.update(b,c(e),f,g,k)}}}var a="undefined"!==
typeof C?C:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.Rb=function(a,c){a.dispose=c};a.C=function(a){for(var c=1,d=arguments,e=d.length-1;c<e;c+=2)a[d[c]]=d[c+1];return a};a.version="2.1.0+mbest/smart-binding/beta.6";a.b("version",a.version);a.a=function(){function b(a,b){if("input"!==i.p(a)||!a.type||"click"!=b.toLowerCase())return r;var c=a.type;return"checkbox"==c||"radio"==c}var c=/^[\s\u00A0]+|[\s\u00A0]+$/g,d={},e={};d[/Firefox\/2/i.test(M.userAgent)?"KeyboardEvent":
"UIEvents"]=["keyup","keydown","keypress"];d.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");for(var f in d){var g=d[f];if(g.length)for(var k=0,l=g.length;k<l;k++)e[g[k]]=f}var j={propertychange:m},h=function(){for(var a=3,b=q.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="<\!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",c[0];);return 4<a?a:n}(),i={$a:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],e:function(a,
b){for(var c=0,d=a.length;c<d;c++)b(a[c])},h:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},Pa:function(a,b,c){for(var d=0,h=a.length;d<h;d++)if(b.call(c,a[d]))return a[d];return p},S:function(a,b){var c=i.h(a,b);0<=c&&a.splice(c,1)},Qa:function(a){for(var a=a||[],b=[],c=0,d=a.length;c<d;c++)0>i.h(b,a[c])&&b.push(a[c]);return b},ba:function(a,b){for(var a=a||[],c=[],d=0,h=a.length;d<
h;d++)c.push(b(a[d]));return c},pa:function(a,b){for(var a=a||[],c=[],d=0,h=a.length;d<h;d++)b(a[d])&&c.push(a[d]);return c},R:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},j:function(a){for(var b=1,c,d;c=arguments[b];b++)for(d in c)c.hasOwnProperty(d)&&(a[d]=c[d]);return a},ec:function(a,b){var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b(a[d]));return c},va:function(b){for(;b.firstChild;)a.T(b.firstChild)},kb:function(b){for(var b=
i.H(b),c=q.createElement("div"),d=0,h=b.length;d<h;d++)a.ca(b[d]),c.appendChild(b[d]);return c},Ta:function(a){for(var b=0,c=a.length,d=[];b<c;b++)d.push(a[b].cloneNode(m));return d},N:function(a,b){i.va(a);if(b)for(var c=0,d=b.length;c<d;c++)a.appendChild(b[c])},qb:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var h=d[0],g=h.parentNode,i=0,e=c.length;i<e;i++)g.insertBefore(c[i],h);i=0;for(e=d.length;i<e;i++)a.T(d[i])}},tb:function(a,b){0<=M.userAgent.indexOf("MSIE 6")?a.setAttribute("selected",
b):a.selected=b},ia:function(a){return(a||"").replace(c,"")},vc:function(a,b){for(var c=[],d=(a||"").split(b),h=0,g=d.length;h<g;h++){var e=i.ia(d[h]);""!==e&&c.push(e)}return c},oc:function(a,b){a=a||"";return b.length>a.length?r:a.substring(0,b.length)===b},Eb:function(a,b){for(var c="return ("+a+")",d=0;d<b;d++)c="with(sc["+d+"]) { "+c+" } ";return new Function("sc",c)},Ob:function(a,b){if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a!=p;){if(a==b)return m;a=a.parentNode}return r},
Ya:function(a){return i.Ob(a,a.ownerDocument)},p:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},o:function(a,c,d){var i=h&&j[c];if(!i&&"undefined"!=typeof s){if(b(a,c))var e=d,d=function(a,b){var c=this.checked;b&&(this.checked=b.Gb!==m);e.call(this,a);this.checked=c};s(a).bind(c,d)}else!i&&"function"==typeof a.addEventListener?a.addEventListener(c,d,r):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,function(b){d.call(a,b)}):o("Browser doesn't support addEventListener or attachEvent")},
ka:function(a,c){(!a||!a.nodeType)&&o("element must be a DOM node when calling triggerEvent");if("undefined"!=typeof s){var d=[];b(a,c)&&d.push({Gb:a.checked});s(a).trigger(c,d)}else"function"==typeof q.createEvent?"function"==typeof a.dispatchEvent?(d=q.createEvent(e[c]||"HTMLEvents"),d.initEvent(c,m,m,x,0,0,0,0,0,r,r,r,r,0,a),a.dispatchEvent(d)):o("The supplied element doesn't support dispatchEvent"):"undefined"!=typeof a.fireEvent?(b(a,c)&&(a.checked=a.checked!==m),a.fireEvent("on"+c)):o("Browser doesn't support triggering events")},
d:function(b){return a.xa(b)?b():b},D:function(b,c,d){return a.i(b,p,{rb:m,Kb:c,Mb:d})},ja:function(a,b,c){if(b){var d=/[\w-]+/g,h=a.className.match(d)||[];i.e(b.match(d),function(a){var b=i.h(h,a);0<=b?c||h.splice(b,1):c&&h.push(a)});a.className=h.join(" ")}},Pb:function(a){if(9<=h){var b=a.style.width;a.style.width=0;a.style.width=b}},ic:function(a,b){for(var a=i.d(a),b=i.d(b),c=[],d=a;d<=b;d++)c.push(d);return c},H:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},Yb:6===h,
Zb:7===h,ea:h,cb:function(a,b){for(var c=i.H(a.getElementsByTagName("input")).concat(i.H(a.getElementsByTagName("textarea"))),d="string"==typeof b?function(a){return a.name===b}:function(a){return b.test(a.name)},h=[],e=c.length-1;0<=e;e--)d(c[e])&&h.push(c[e]);return h},fc:function(a){return"string"==typeof a&&(a=i.ia(a))?x.JSON&&x.JSON.parse?x.JSON.parse(a):(new Function("return "+a))():p},Ha:function(a,b,c){("undefined"==typeof JSON||"undefined"==typeof JSON.stringify)&&o("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");
return JSON.stringify(i.d(a),b,c)},gc:function(a,b,c){var c=c||{},d=c.params||{},h=c.includeFields||this.$a,e=a;if("object"==typeof a&&"form"===i.p(a))for(var e=a.action,g=h.length-1;0<=g;g--)for(var l=i.cb(a,h[g]),f=l.length-1;0<=f;f--)d[l[f].name]=l[f].value;var b=i.d(b),k=q.createElement("form");k.style.display="none";k.action=e;k.method="post";for(var j in b)a=q.createElement("input"),a.name=j,a.value=i.Ha(i.d(b[j])),k.appendChild(a);for(j in d)a=q.createElement("input"),a.name=j,a.value=d[j],
k.appendChild(a);q.body.appendChild(k);c.submitter?c.submitter(k):k.submit();setTimeout(function(){k.parentNode.removeChild(k)})}};return a.C(i,"arrayForEach",i.e,"arrayFirst",i.Pa,"arrayFilter",i.pa,"arrayGetDistinctValues",i.Qa,"arrayIndexOf",i.h,"arrayMap",i.ba,"arrayPushAll",i.R,"arrayRemoveItem",i.S,"extend",i.j,"fieldsIncludedWithJsonPost",i.$a,"getFormFields",i.cb,"possiblyWrap",i.D,"postJson",i.gc,"parseJson",i.fc,"registerEventHandler",i.o,"stringifyJson",i.Ha,"range",i.ic,"toggleDomNodeCssClass",
i.ja,"triggerEvent",i.ka,"unwrapObservable",i.d)}();a.b("utils",a.a);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this,d=Array.prototype.slice.call(arguments),a=d.shift();return function(){return c.apply(a,d.concat(Array.prototype.slice.call(arguments)))}});a.a.z=new function(){function b(a,b){var c=d(a,r);return c===n?n:c[b]}function c(a,b,c){c===n&&d(a,r)===n||(d(a,m)[b]=c)}function d(a,b){var c=a[f];if(!(c&&"null"!==c)){if(!b)return n;c=a[f]="ko"+e++;g[c]={}}return g[c]}
var e=0,f="__ko__"+(new Date).getTime(),g={};a.s=b;a.n=c;return{get:b,set:c,clear:function(a){var b=a[f];b&&(delete g[b],a[f]=p)},M:function(){return e++}}};a.b("utils.domData",a.a.z);a.b("utils.domData.clear",a.a.z.clear);a.a.Xa=new function(){function b(b,c){var d=a.s(b,e);d===n&&c&&(d=[],a.n(b,e,d));return d}function c(d,f){var h=b(d,r);if(h){for(var h=h.slice(0),i=0;i<h.length;i++)h[i](d);f&&a.n(d,e,n)}f||(a.a.z.clear(d),"function"==typeof s&&"function"==typeof s.cleanData&&s.cleanData([d]));
if(g[d.nodeType])for(i=d.firstChild;h=i;)i=h.nextSibling,8===h.nodeType&&c(h,f)}function d(b,d){if(f[b.nodeType]&&(c(b,d),g[b.nodeType])){var h=[];a.a.R(h,b.getElementsByTagName("*"));for(var e=0,k=h.length;e<k;e++)c(h[e],d)}}var e=a.a.z.M(),f={1:m,8:m,9:m},g={1:m,9:m};a.ca=d;a.T=function(a){d(a);a.parentNode&&a.parentNode.removeChild(a)};a.sc=function(a){d(a,m)};var k={La:function(c,d,h){function g(a){t.push(a);3!==a.nodeType&&b(a,m).push(f)}function f(b,c){c?c==d&&y(b):(a.a.S(t,b),t.length||d())}
function k(b){b.nodeType?g(b):a.a.e(b,g)}function y(c){if(3!==c.nodeType){var d=b(c,r);d&&(a.a.S(d,f),d.length||a.n(c,e,n))}a.a.S(t,c)}function L(){for(;t.length;)y(t[0])}var t=[];"function"!=typeof d&&o("Callback must be a function");c&&k(c);return{Ab:k,rc:y,Jb:L,m:function(){L();d()},nc:function(){return t.length&&!a.a.Pa(t,a.a.Ya)||h&&h()},Tb:function(){return t},tc:function(){return t.length}}},jc:function(c,d){var h=b(c,r);if(h)var e=a.a.H(h);a.a.e(e,function(a){a(c,d)})}};return a.C(k,"addDisposeCallback",
k.La,"removeDisposeCallback",k.jc)};a.b("cleanNode",a.ca);a.b("cleanAndRemoveNode",a.T);a.b("removeNode",a.T);a.b("utils.domNodeDisposal",a.a.Xa);(function(){a.a.Da=function(b){var c;if("undefined"!=typeof s){if((c=s.clean([b]))&&c[0]){for(b=c[0];b.parentNode&&11!==b.parentNode.nodeType;)b=b.parentNode;b.parentNode&&b.parentNode.removeChild(b)}}else{var d=a.a.ia(b).toLowerCase();c=q.createElement("div");d=d.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!d.indexOf("<tr")&&[2,"<table><tbody>",
"</tbody></table>"]||(!d.indexOf("<td")||!d.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];b="ignored<div>"+d[1]+b+d[2]+"</div>";for("function"==typeof x.innerShiv?c.appendChild(x.innerShiv(b)):c.innerHTML=b;d[0]--;)c=c.lastChild;c=a.a.H(c.lastChild.childNodes)}return c};a.a.ha=function(b,c){a.a.va(b);if(c!==p&&c!==n)if("string"!=typeof c&&(c=c.toString()),"undefined"!=typeof s)s(b).html(c);else for(var d=a.a.Da(c),e=0;e<d.length;e++)b.appendChild(d[e])}})();a.b("utils.parseHtmlFragment",
a.a.Da);a.b("utils.setHtml",a.a.ha);a.W=function(){function b(){return(4294967296*(1+Math.random())|0).toString(16).substring(1)}function c(b,d){if(b)if(8==b.nodeType){var e=a.W.mb(b.nodeValue);e!=p&&d.push({Nb:b,cc:e})}else if(1==b.nodeType)for(var e=0,l=b.childNodes,j=l.length;e<j;e++)c(l[e],d)}var d={},e={Aa:function(a){"function"!=typeof a&&o("You can only pass a function to ko.memoization.memoize()");var c=b()+b();d[c]=a;return"<\!--[ko_memo:"+c+"]--\>"},xb:function(a,b){var c=d[a];c===n&&o("Couldn't find any memo with ID "+
a+". Perhaps it's already been unmemoized.");try{return c.apply(p,b||[]),m}finally{delete d[a]}},yb:function(b,d){var k=[];c(b,k);for(var l=0,j=k.length;l<j;l++){var h=k[l].Nb,i=[h];d&&a.a.R(i,d);e.xb(k[l].cc,i);h.nodeValue="";h.parentNode&&h.parentNode.removeChild(h)}},mb:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:p}};return a.C(e,"memoize",e.Aa,"unmemoize",e.xb,"parseMemoText",e.mb,"unmemoizeDomNodeAndDescendants",e.yb)}();a.b("memoization",a.W);a.Za={throttle:function(b,c){if(a.ya(b)){var d=
p;return a.i({read:b,write:function(a){clearTimeout(d);d=setTimeout(function(){b(a)},c)}})}b.throttleEvaluation=c;return b},notify:function(b,c){b.equalityComparer="always"==c?function(){return r}:a.k.fn.equalityComparer;return b}};a.b("extenders",a.Za);a.vb=function(b,c,d){this.target=b;this.sa=c;this.Lb=d;a.Rb(this,this.m)};a.vb.prototype.m=function(){this.Xb=m;this.Lb()};a.u=function(){this.v={};a.a.j(this,a.u.fn);a.C(this,"subscribe",this.Ia,"extend",this.extend,"getSubscriptionsCount",this.Ub)};
a.u.fn={Ia:function(b,c,d){var d=d||"change",e=this,b=c?b.bind(c):b,f=new a.vb(e,b,function(){a.a.S(e.v[d],f)});e.v[d]||(e.v[d]=[]);e.v[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";this.v[c]&&a.a.e(this.v[c].slice(0),function(a){a&&a.Xb!==m&&a.sa(b)})},Ub:function(){var a=0,c;for(c in this.v)this.v.hasOwnProperty(c)&&(a+=this.v[c].length);return a},extend:function(b){var c=this;if(b)for(var d in b){var e=a.Za[d];"function"==typeof e&&(c=e(c,b[d]))}return c}};a.jb=function(a){return"function"==
typeof a.Ia&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.u);a.b("isSubscribable",a.jb);a.q=function(){var b=[];return{Ra:function(a){b.push({sa:a,Wa:[]})},end:function(){b.pop()},Y:function(c){a.jb(c)||o("Only subscribable things can act as dependencies");if(0<b.length){var d=b[b.length-1];d&&!(0<=a.a.h(d.Wa,c))&&(d.Wa.push(c),d.sa(c))}},fb:function(a){try{return b.push(p),a()}finally{b.pop()}}}}();a.b("ignoreDependencies",a.uc=a.q.fb);var T={undefined:m,"boolean":m,number:m,string:m};
a.k=function(b){function c(){if(0<arguments.length){if(!c.equalityComparer||!c.equalityComparer(d,arguments[0]))c.J(),d=arguments[0],c.I();return this}a.q.Y(c);return d}var d=b;a.u.call(c);c.ga=function(){return d};c.I=function(){c.notifySubscribers(d)};c.J=function(){c.notifySubscribers(d,"beforeChange")};a.a.j(c,a.k.fn);return a.C(c,"peek",c.ga,"valueHasMutated",c.I,"valueWillMutate",c.J)};a.k.fn={equalityComparer:function(a,c){return a===p||typeof a in T?a===c:r}};var B=a.k.hc="__ko_proto__";a.k.fn[B]=
a.k;a.wa=function(b,c){return b===p||b===n||b[B]===n?r:b[B]===c?m:a.wa(b[B],c)};a.xa=function(b){return a.wa(b,a.k)};a.ya=function(b){return"function"==typeof b&&b[B]===a.k||"function"==typeof b&&b[B]===a.i&&b.Vb?m:r};a.b("observable",a.k);a.b("isObservable",a.xa);a.b("isWriteableObservable",a.ya);a.X=function(b){0==arguments.length&&(b=[]);b!==p&&(b!==n&&!("length"in b))&&o("The argument passed when initializing an observable array must be an array, or null, or undefined.");var c=a.k(b);a.a.j(c,
a.X.fn);return c};a.X.fn={remove:function(a){for(var c=this(),d=[],e="function"==typeof a?a:function(c){return c===a},f=0;f<c.length;f++){var g=c[f];e(g)&&(0===d.length&&this.J(),d.push(g),c.splice(f,1),f--)}d.length&&this.I();return d},removeAll:function(b){if(b===n){var c=this(),d=c.slice(0);this.J();c.splice(0,c.length);this.I();return d}return!b?[]:this.remove(function(c){return 0<=a.a.h(b,c)})},destroy:function(a){var c=this(),d="function"==typeof a?a:function(c){return c===a};this.J();for(var e=
c.length-1;0<=e;e--)d(c[e])&&(c[e]._destroy=m);this.I()},destroyAll:function(b){return b===n?this.destroy(function(){return m}):!b?[]:this.destroy(function(c){return 0<=a.a.h(b,c)})},indexOf:function(b){var c=this();return a.a.h(c,b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.J(),this()[d]=c,this.I())}};a.a.e("pop push reverse shift sort splice unshift".split(" "),function(b){a.X.fn[b]=function(){var a=this();this.J();a=a[b].apply(a,arguments);this.I();return a}});a.a.e(["slice"],function(b){a.X.fn[b]=
function(){var a=this();return a[b].apply(a,arguments)}});a.b("observableArray",a.X);a.i=function(b,c,d){function e(){a.a.e(t,function(a){a.m()});t=[];u=r}function f(){u=m;var a=l.throttleEvaluation;a&&0<=a?(clearTimeout(P),P=setTimeout(k,a)):k()}function g(a){t.push(a.Ia(f))}function k(){if(!w&&u)if(s&&s())l.m();else{w=m;try{var b=a.a.ba(t,function(a){return a.target});a.q.Ra(function(c){var d;0<=(d=a.a.h(b,c))?b[d]=n:g(c)});for(var d=y.call(c),h=b.length-1;0<=h;h--)b[h]&&t.splice(h,1)[0].m();u=
r;l.notifySubscribers(i,"beforeChange");i=d}finally{a.q.end()}l.notifySubscribers(i);w=r}}function l(){if(0<arguments.length)j.apply(l,arguments);else return u&&k(),a.q.Y(l),i}function j(){"function"===typeof L?L.apply(c,arguments):o("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.")}function h(b){b&&(q||(q=a.a.Xa.La(p,e,s)),q.Ab(b),l.m=q.m,s=q.nc,v=q.Tb());return l}var i,u=m,w=r,y=b;y&&"object"==typeof y?
(d=y,y=d.read):(d=d||{},y||(y=d.read));"function"!=typeof y&&o("Pass a function that returns the value of the ko.computed");var L=d.write;c||(c=d.owner);var t=[],P=p;if(d.deferEvaluation!==m||d.rb){w=m;try{a.q.Ra(g),i=y.call(c)}finally{a.q.end()}u=w=r}if(d.rb&&!t.length)return i;l.ga=function(){u&&k();return i};var q,v=[];a.a.j(l,{Vb:"function"===typeof L,bb:function(){return t.length},$:h,Fa:function(a){q&&q.Jb();return h(a)},Sb:function(){return v.length},m:e});var s=d.Mb||d.disposeWhen;h(d.Kb||
d.disposeWhenNodeIsRemoved);a.u.call(l);a.a.j(l,a.i.fn);return a.C(l,"peek",l.ga,"dispose",l.m,"getDependenciesCount",l.bb,"addDisposalNodes",l.$,"replaceDisposalNodes",l.Fa,"getDisposalNodesCount",l.Sb)};a.Wb=function(b){return a.wa(b,a.i)};C=a.k.hc;a.i[C]=a.k;a.i.fn={};a.i.fn[C]=a.i;a.b("dependentObservable",a.i);a.b("computed",a.i);a.b("isComputed",a.Wb);(function(){function b(a,f,g){g=g||new d;a=f(a);if(!("object"==typeof a&&a!==p&&a!==n&&!(a instanceof Date)))return a;var k=a instanceof Array?
[]:{};g.save(a,k);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":k[c]=d;break;case "object":case "undefined":var h=g.get(d);k[c]=h!==n?h:b(d,f,g)}});return k}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){var b=[],c=[];this.save=function(d,k){var l=a.a.h(b,d);0<=l?c[l]=k:(b.push(d),c.push(k))};this.get=function(d){d=a.a.h(b,d);return 0<=d?c[d]:
n}}a.wb=function(c){0==arguments.length&&o("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.xa(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.wb(b);return a.a.Ha(b,c,d)}})();a.b("toJS",a.wb);a.b("toJSON",a.toJSON);a.r=function(){var b={t:function(c){switch(a.a.p(c)){case "option":return c.__ko__hasDomDataOptionValue__===m?a.s(c,a.c.options.Ca):7>=a.a.ea?c.getAttributeNode("value").specified?c.value:c.text:c.value;case "select":return 0<=
c.selectedIndex?b.t(c.options[c.selectedIndex]):n;default:return c.value}},la:function(c,d){switch(a.a.p(c)){case "option":switch(typeof d){case "string":a.n(c,a.c.options.Ca,n);"__ko__hasDomDataOptionValue__"in c&&delete c.__ko__hasDomDataOptionValue__;c.value=d;break;default:a.n(c,a.c.options.Ca,d),c.__ko__hasDomDataOptionValue__=m,c.value="number"===typeof d?d:""}break;case "select":for(var e=c.options.length-1;0<=e;e--)if(b.t(c.options[e])==d){c.selectedIndex=e;break}break;default:if(d===p||d===
n)d="";c.value=d}}};return a.C(b,"readValue",b.t,"writeValue",b.la)}();a.b("selectExtensions",a.r);a.w=function(){function b(b){var c=a.a.ia(b);123===c.charCodeAt(0)&&(c=c.slice(1,-1));var b=[],c=c.match(e),d,l,j=0;if(c){c.push(",");for(var h=0,i=c.length;h<i;++h){var u=c[h],w=u.charCodeAt(0);if(44===w){if(0>=j){d&&b.push([d,l?l.join(""):n]);d=l=j=0;continue}}else if(58===w){if(!l)continue}else if(40===w||123===w||91===w)++j;else if(41===w||125===w||93===w)--j;else if(!d){d=34===w||39===w?u.slice(1,
-1):u;continue}l?l.push(u):l=[u]}}return b}var c=/^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/i,d=["true","false","null"],e=RegExp("(?:(?:\"(?:[^\"\\\\]|\\\\.)*\")|(?:'(?:[^'\\\\]|\\\\.)*')|(?:/(?:[^/\\\\]|\\\\.)*/)|(?:[^\\s:,][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]])|[^\\s])","g");return{nb:b,ob:function(e,g){function k(e,g,f){var u="'"+e+"'",o=f||a.ab(e),q=o||i,v=o&&o.flags;g===n&&v&128&&(g="true");if(!f&&v&4&&"{"===g.charAt(0))g=b(g),a.a.e(g,function(a){k(e+"."+a[0],a[1],
o)});else{if(o&&o.preprocess&&(g=o.preprocess(g,e,k),!g))return;if(g.match(/^[\(\s]*function\s*\(.*}[\)\s]*$/)===p){if(o&&(0<=a.a.h(d,g)?0:g.match(c)!==p))h&&v&2?(g="function(_x,_y,_z){("+g+")(_x,_y,_z);}",q=r):v&1&&j.push(u+":function(_z){"+g+"=_z;}");q&&g.match(/[^(]+\(/)!==p&&(g="ko.bindingValueWrap(function(){return "+g+"})")}l.push(u+":"+g)}}var g=g||{},l=[],j=[],h=g.eventHandlersUseObjectForThis,i=g.independentBindings,u="string"===typeof e?b(e):e;a.a.e(u,function(a){k(a[0],a[1])});u=l.join(",");
0<j.length&&(u=u+",'_ko_property_writers':{"+j.join(",")+"}");return u},ac:function(a,b){for(var c=0;c<a.length;c++)if(a[c][0]==b)return m;return r},ma:function(b,c,d,e,j){if(!b||!a.ya(b)){if((b=c("_ko_property_writers"))&&b[d])b[d](e)}else(!j||b()!==e)&&b(e)}}}();a.f=function(){function b(a){return 8==a.nodeType&&(f?a.text:a.nodeValue).match(g)}function c(a){return 8==a.nodeType&&(f?a.text:a.nodeValue).match(k)}function d(a,d){for(var e=a,g=1,l=[];e=e.nextSibling;){if(c(e)&&(g--,0===g))return l;
l.push(e);b(e)&&g++}d||o("Cannot find closing comment tag to match: "+a.nodeValue);return p}function e(a,b){var c=d(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:p}var f="<\!--test--\>"===q.createComment("test").text,g=f?/^<\!--\s*ko\s+(.*\:.*)\s*--\>$/:/^\s*ko\s+(.*\:.*)\s*$/,k=f?/^<\!--\s*\/ko\s*--\>$/:/^\s*\/ko\s*$/,l={ul:m,ol:m},j={Ma:{},childNodes:function(a){return b(a)?d(a):a.childNodes},da:function(c){if(b(c))for(var c=j.childNodes(c),d=0,e=c.length;d<e;d++)a.T(c[d]);else a.a.va(c)},
N:function(c,d){if(b(c)){j.da(c);for(var e=c.nextSibling,g=0,l=d.length;g<l;g++)e.parentNode.insertBefore(d[g],e)}else a.a.N(c,d)},pb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},hb:function(a,c,d){b(a)?a.parentNode.insertBefore(c,d.nextSibling):d.nextSibling?a.insertBefore(c,d.nextSibling):a.appendChild(c)},firstChild:function(a){return!b(a)?a.firstChild:!a.nextSibling||c(a.nextSibling)?p:a.nextSibling},nextSibling:function(a){b(a)&&
(a=e(a));return a.nextSibling&&c(a.nextSibling)?p:a.nextSibling},qc:function(a){return(a=b(a))?a[1]:p},lb:function(d){if(l[a.a.p(d)]){var g=d.firstChild;if(g){do if(1===g.nodeType){var f;f=g.firstChild;var k=p;if(f){do if(k)k.push(f);else if(b(f)){var j=e(f,m);j?f=j:k=[f]}else c(f)&&(k=[f]);while(f=f.nextSibling)}if(f=k){k=g.nextSibling;for(j=0;j<f.length;j++)k?d.insertBefore(f[j],k):d.appendChild(f[j])}}while(g=g.nextSibling)}}}};return a.C(j,"allowedBindings",j.Ma,"emptyNode",j.da,"insertAfter",
j.hb,"prepend",j.pb,"setDomNodeChildren",j.N)}();a.b("virtualElements",a.f);(function(){a.K=function(){this.Sa={};this.clearCache=function(){this.Sa={}}};a.a.j(a.K.prototype,{nodeHasBindings:function(a){return!!this.getBindingsString(a)},getBindings:function(a,c){var d=this.getBindingsString(a);return d?this.parseBindingsString(d,c):p},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.f.qc(b);default:return p}},parseBindingsString:function(b,
c){try{var d=c.$data,d="object"==typeof d&&d!=p?[d,c]:[c],e=d.length,f=this.Sa,g=e+"_"+b,k;if(!(k=f[g])){var l=" { "+a.w.ob(b,c.$options)+" } ";k=f[g]=a.a.Eb(l,e)}return k(d)}catch(j){o("Unable to parse bindings.\nMessage: "+j+";\nBindings value: "+b)}}});a.K.instance=new a.K})();a.b("bindingProvider",a.K);(function(){function b(b,c){var d=b.indexOf(".");if(0<d){var e=b.substring(0,d),g=a.c[e];if(g)return g.flags&4||o(e+" does not support two-level binding"),c?g:{key:e,pc:b.substring(d+1),G:g}}}function c(c){var d=
a.c[c];return d?{G:d,key:c}:b(c)}function d(b){return b&&b.Ka&&b.Ka===a.ra?b():b}function e(b,c,d){for(var e=a.f.firstChild(c);c=e;)e=a.f.nextSibling(c),f(b,c,d)}function f(b,g,f,j,y){function q(a,b){return b?function(){J&&J();var c={};c[b]=d(z[a]);return c}:function(){J&&J();return d(z[a])}}function t(b){return b?d(z[b]):a.a.ec(B,d)}function s(a){return a?z[a]:z}function x(a,b){o("Multiple bindings ("+a+" and "+b+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")}
function v(a){return function(){var c=(0,a.G.init)(g,a.zb,C,K,b);c&&(!(a.V&16)&&c.controlsDescendantBindings)&&(D?o(a.key+" binding handler must be updated to use contentBind flag"):G[2]?x(G[2].key,a.key):G[a.A=2]=a);return c&&c.subscribable}}function H(c){return function(){c.Ba&&a.a.e(c.Ba,function(b){b.u&&a.q.Y(b.u)});return(0,c.G.update)(g,c.zb,C,K,b)}}function A(b){N&&b.G.init&&(b.u=a.q.fb(v(b)));b.G.update&&(b.u=a.a.D(H(b),g)||b.u)}function I(a){a.G.update&&H(a)()}var F=1===g.nodeType,Q=j||a.K.instance.nodeHasBindings(g),
D=b.$options.independentBindings;F&&a.f.lb(g);f&&(F||Q)&&a.ub(g,b);if(Q){var z,B={},K=b.$data,N=m,J=a.a.D(function(){a.c[k]=l;z=("function"==typeof j?j():j)||a.K.instance.getBindings(g,b);if(D&&!N)for(var c in B)B[c]=z[c];z&&b.B&&a.q.Y(b.B)},g);D&&(J&&(!b.B||1<J.bb()))&&o("In independent mode, binding provider must not access any observables.");var C=D?t:s,O=D?A:I,E=[],G=[[],[],n,[]];a.a.D(function(){if(N){var d={},f=z&&z[k]||{},l=0,j,u=function(b){if(b in d)return E[d[b]];var e=c(b);if(e){var g=
e.G,h;e.V=g.flags;!F&&(!a.f.Ma[e.key]&&!(e.V&64))&&o("The binding '"+e.key+"' cannot be used with virtual elements");e.zb=q(b,e.pc);!D&&g.init&&v(e)();e.V&16?(G[2]&&x(G[2].key,e.key),G[e.A=2]=e,h=1):h=e.A=e.V&8?1:e.V&32?3:0;if(g[k]||f[b])d[b]=-1,e.Ba=[],a.a.e([].concat(g[k]||[],f[b]||[]),function(a){var c;(!(a in z)||!(c=u(a)))&&o("Binding "+b+" cannot 'need' "+a+": missing or recursive");e.A?c.A<=e.A?c.Va=Math.min(c.Va||3,h):o("Binding "+b+" cannot 'need' "+a+": conflicting ordering"):e.A=c.A;e.Ba.push(c)});
d[b]=E.push(e)-1;return e}D&&(B[b]=z[b])};for(j in z)u(j);for(var w=0,n;n=E[w];w++)2==n.A?j=3:(j=n.A||n.Va||l,G[j].push(n)),j>l&&(l=j)}!D&&J&&J();a.a.e(G[0],O);a.a.e(G[1],O);G[2]?O(G[2]):y||e(b,g,!F);a.a.e(G[3],O)},g);N=y=r}else y||e(b,g,!F)}function g(b,c){return b&&b instanceof a.F?b:new a.F(b,p,c)}a.Db={twoWay:1,eventHandler:2,contentBind:16,contentSet:8,contentUpdate:32,noValue:128,twoLevel:4,canUseVirtual:64};a.Fb=function(a){return a.flags&16&&!(a.flags&8)};a.c={};a.F=function(b,c,d,e){var g=
this,f="function"==typeof b,l;g.B=l=a.a.D(function(){var k=f?b():b;c?(c.B&&a.q.Y(c.B),a.a.j(g,c),g.B=l,g.$options=a.a.j({},c.$options,d)):(g.$parents=[],g.$root=k,g.$options=a.a.j({},d));g.$data=k;e&&e(g,c,k)})};a.a.j(a.F.prototype,{createChildContext:function(b,c){return new a.F(b,this,p,function(a,b,d){a.$parentContext=b;a.$parents=b.$parents.slice(0);a.$parents.unshift(a.$parent=b.$data);c&&(a[c]=d)})},extend:function(b){return new a.F(p,this,p,function(c,d){c.$data=d.$data;a.a.j(c,"function"==
typeof b?b():b)})}});a.ab=function(c){return a.c[c]||b(c,m)};a.ra=function(b){b.Ka=a.ra;return b};var k="needs",l={flags:512},j=a.a.z.M();a.ub=function(b,c){if(2==arguments.length)a.n(b,j,c),c.B&&c.B.$(b);else return a.s(b,j)};a.Oa=function(b,c,d,e){1===b.nodeType&&a.f.lb(b);f(g(d),b,m,c,!e)};a.aa=function(a,b){(1===b.nodeType||8===b.nodeType)&&e(g(a),b,m)};a.Na=function(a,b,c){b&&(1!==b.nodeType&&8!==b.nodeType)&&o("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");
b=b||x.document.body;f(g(a,c),b,m)};a.ua=function(b){switch(b.nodeType){case 1:case 8:var c=a.ub(b);if(c)return c;if(b.parentNode)return a.ua(b.parentNode)}return n};a.Ib=function(b){return(b=a.ua(b))?b.$data:n};a.b("bindingHandlers",a.c);a.b("bindingFlags",a.Db);a.b("bindingValueWrap",a.ra);a.b("applyBindings",a.Na);a.b("applyBindingsToDescendants",a.aa);a.b("applyBindingsToNode",a.Oa);a.b("contextFor",a.ua);a.b("dataFor",a.Ib)})();a.a.e(["click"],function(b){a.c[b]={preprocess:function(a,d,e){e("event."+
b,a)},flags:2,init:function(c,d,e,f){return a.c.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f)}}});a.c.event={flags:6,init:function(b,c,d,e){var f=c()||{},g;for(g in f)(function(){var f=g;"string"==typeof f&&a.a.o(b,f,function(b){var g,h=c()[f];if(h){try{var i=a.a.H(arguments);i.unshift(e);g=h.apply(e,i)}finally{g!==m&&(b.preventDefault?b.preventDefault():b.returnValue=r)}d(f+"Bubble")===r&&(b.cancelBubble=m,b.stopPropagation&&b.stopPropagation())}})})()}};a.c.submit={flags:2,
init:function(b,c,d,e){"function"!=typeof c()&&o("The value for a submit binding must be a function");a.a.o(b,"submit",function(a){var d,k=c();try{d=k.call(e,b)}finally{d!==m&&(a.preventDefault?a.preventDefault():a.returnValue=r)}})}};a.c.visible={update:function(b,c){var d=a.a.d(c()),e="none"!=b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};a.c.enable={update:function(b,c){var d=a.a.d(c());d&&b.disabled?b.removeAttribute("disabled"):!d&&!b.disabled&&(b.disabled=m)}};a.c.disable=
{update:function(b,c){return a.c.enable.update(b,function(){return!a.a.d(c())})}};a.c.value={flags:33,init:function(b,c,d){function e(){var e=c(),g=a.r.t(b);a.w.ma(e,d,"value",g,m)}var f=["change"],g=d("valueUpdate");g&&("string"==typeof g&&(g=[g]),a.a.R(f,g),f=a.a.Qa(f));if(a.a.ea&&("input"==b.tagName.toLowerCase()&&"text"==b.type&&"off"!=b.autocomplete&&(!b.form||"off"!=b.form.autocomplete))&&-1==a.a.h(f,"propertychange")){var k=r;a.a.o(b,"propertychange",function(){k=m});a.a.o(b,"blur",function(){if(k){k=
r;e()}})}a.a.e(f,function(c){var d=e;if(a.a.oc(c,"after")){d=function(){setTimeout(e,0)};c=c.substring(5)}a.a.o(b,c,d)})},update:function(b,c){var d="select"===a.a.p(b),e=a.a.d(c()),f=a.r.t(b),g=e!=f;0===e&&(0!==f&&"0"!==f)&&(g=m);g&&(f=function(){a.r.la(b,e)},f(),d&&(e!==a.r.t(b)?a.a.ka(b,"change"):setTimeout(f)))}};a.c.options={flags:24,update:function(b,c,d){"select"!==a.a.p(b)&&o("options binding applies only to SELECT elements");for(var e=a.a.ba(a.a.pa(b.childNodes,function(b){return b.tagName&&
"option"===a.a.p(b)&&b.selected}),function(b){return a.r.t(b)||b.innerText||b.textContent}),f=b.scrollTop,g=a.a.d(c());0<b.length;)a.ca(b.options[0]),b.remove(0);if(g){var k=d();"number"!=typeof g.length&&(g=[g]);if(k.optionsCaption){var l=q.createElement("option");a.a.ha(l,k.optionsCaption);a.r.la(l,n);b.appendChild(l)}d=0;for(c=g.length;d<c;d++){var l=q.createElement("option"),j="string"==typeof k.optionsValue?g[d][k.optionsValue]:g[d],j=a.a.d(j);a.r.la(l,j);var h=k.optionsText,j="function"==typeof h?
h(g[d]):"string"==typeof h?g[d][h]:j,j=a.a.d(j);l.appendChild(q.createTextNode(j===p||j===n?"":j));b.appendChild(l)}g=b.getElementsByTagName("option");d=k=0;for(c=g.length;d<c;d++)0<=a.a.h(e,a.r.t(g[d]))&&(a.a.tb(g[d],m),k++);b.scrollTop=f;k<e.length&&a.a.ka(b,"change");a.a.Pb(b)}}};a.c.options.Ca=a.a.z.M();a.c.selectedOptions={flags:33,eb:function(b){for(var c=[],b=b.childNodes,d=0,e=b.length;d<e;d++){var f=b[d],g=a.a.p(f);"option"==g&&f.selected?c.push(a.r.t(f)):"optgroup"==g&&(f=a.c.selectedOptions.eb(f),
Array.prototype.splice.apply(c,[c.length,0].concat(f)))}return c},init:function(b,c,d){a.a.o(b,"change",function(){var b=c(),f=a.c.selectedOptions.eb(this);a.w.ma(b,d,"value",f)})},update:function(b,c){"select"!=a.a.p(b)&&o("values binding applies only to SELECT elements");var d=a.a.d(c());if(d&&"number"==typeof d.length)for(var e=b.childNodes,f=0,g=e.length;f<g;f++){var k=e[f];"option"===a.a.p(k)&&a.a.tb(k,0<=a.a.h(d,a.r.t(k)))}}};a.c.text={flags:88,init:function(b){a.f.N(b,[q.createTextNode("")])},
update:function(b,c){var d=a.a.d(c());a.f.firstChild(b).data=d===p||d===n?"":d}};a.c.html={flags:24,update:function(b,c){var d=a.a.d(c());a.a.ha(b,d)}};a.c.css={flags:4,update:function(b,c){var d=a.a.d(c());if("object"==typeof d)for(var e in d){var f=a.a.d(d[e]);a.a.ja(b,e,f)}else d=""+(d||""),a.a.ja(b,b.__ko__cssValue,r),b.__ko__cssValue=d,a.a.ja(b,d,m)}};a.c.style={flags:4,update:function(b,c){var d=a.a.d(c()||{}),e;for(e in d)if("string"==typeof e){var f=a.a.d(d[e]);b.style[e]=f||""}}};a.c.uniqueName=
{flags:128,init:function(b,c){c()&&(b.name="ko_unique_"+ ++a.c.uniqueName.Hb,(a.a.Yb||a.a.Zb)&&b.mergeAttributes(q.createElement("<input name='"+b.name+"'/>"),r))}};a.c.uniqueName.Hb=0;a.c.checked={flags:1,init:function(b,c,d){a.a.o(b,"click",function(){var e;if("checkbox"==b.type)e=b.checked;else if("radio"==b.type&&b.checked)e=b.value;else return;var f=c();"checkbox"==b.type&&a.a.d(f)instanceof Array?(e=a.a.h(a.a.d(f),b.value),b.checked&&0>e?f.push(b.value):!b.checked&&0<=e&&f.splice(e,1)):a.w.ma(f,
d,"checked",e,m)});"radio"==b.type&&!b.name&&a.c.uniqueName.init(b,function(){return m})},update:function(b,c){var d=a.a.d(c());"checkbox"==b.type?b.checked=d instanceof Array?0<=a.a.h(d,b.value):d:"radio"==b.type&&(b.checked=b.value==d)}};var R={"class":"className","for":"htmlFor"};a.c.attr={flags:4,update:function(b,c){var d=a.a.d(c())||{},e;for(e in d)if("string"==typeof e){var f=a.a.d(d[e]),g=f===r||f===p||f===n;g&&b.removeAttribute(e);8>=a.a.ea&&e in R?(e=R[e],g?b.removeAttribute(e):b[e]=f):
g||b.setAttribute(e,f.toString())}}};a.c.withlight={flags:80,preprocess:function(a,c,d){(c=a.match(/^\s*([$\w]+)\s*=\s*([^=][\s\S]*)$/))&&d("withItemName",'"'+c[1]+'"');return c?c[2]:a},init:function(b,c,d,e,f){d=f.createChildContext(function(){return a.a.d(c())},d("withItemName"));a.aa(d,b)}};a.c.hasfocus={flags:1,init:function(b,c,d){function e(b){var e=c();a.w.ma(e,d,"hasfocus",b,m)}a.a.o(b,"focus",function(){e(m)});a.a.o(b,"focusin",function(){e(m)});a.a.o(b,"blur",function(){e(r)});a.a.o(b,"focusout",
function(){e(r)})},update:function(b,c){var d=a.a.d(c());d?b.focus():b.blur();a.a.ka(b,d?"focusin":"focusout")}};var S=a.a.z.M();a.c["with"]={flags:80,init:function(b,c,d,e,f){c=a.a.d(c());d=a.f.childNodes(b);e=a.k(c);c&&(d=a.a.Ta(d),a.aa(f.createChildContext(e),b));a.n(b,S,{mc:a.a.kb(d),lc:e})},update:function(b,c,d,e,f){d=a.s(b,S);e=d.lc;c=a.a.d(c());e.ga()?(c||a.f.da(b),e(c)):c&&(nodesArray=a.a.Ta(d.mc.childNodes),a.f.N(b,nodesArray),e(c),a.aa(f.createChildContext(e),b))}};a.c["if"]=E(function(a,
c){c["if"]=a});a.c.ifnot=E(function(a,c){c.ifnot=a});a.c.foreach=E(function(b,c){!b||"number"==typeof b.length?c.foreach=b:(a.a.j(c,b),c.foreach=c.data,delete c.name)});a.Z=function(){};a.a.j(a.Z.prototype,{renderTemplateSource:function(){o("Override renderTemplateSource")},createJavaScriptEvaluatorBlock:function(){o("Override createJavaScriptEvaluatorBlock")},makeTemplateSource:function(b,c){if("string"==typeof b){var c=c||q,d=c.getElementById(b);d||o("Cannot find template with ID "+b);return new a.l.g(d)}if(1==
b.nodeType||8==b.nodeType)return new a.l.Q(b);o("Unknown template type: "+b)},renderTemplate:function(a,c,d,e){return this.renderTemplateSource(this.makeTemplateSource(a,e),c,d)},isTemplateRewritten:function(a,c){return this.allowTemplateRewriting===r||!(c&&c!=q)&&this.fa&&this.fa[a]?m:this.makeTemplateSource(a,c).data("isRewritten")},rewriteTemplate:function(a,c,d){var e=this.makeTemplateSource(a,d),c=c(e.text());e.text(c);e.data("isRewritten",m);!(d&&d!=q)&&"string"==typeof a&&(this.fa=this.fa||
{},this.fa[a]=m)}});a.b("templateEngine",a.Z);a.O=function(){function b(b,c,d){for(var b=a.w.nb(b),k=a.O.qa,l=0;l<b.length;l++){var j=b[l][0];if(k.hasOwnProperty(j))(j=k[j](b[l][1]))&&o(j);else{var h=a.ab(j);h&&a.Fb(h)&&o("This template engine does not support the '"+j+"' binding within its templates")}}b="ko.__tr_ambtns(function(){return(function(){return{"+a.w.ob(b)+"} })()})";return d.createJavaScriptEvaluatorBlock(b)+c}var c=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi,
d=/<\!--\s*ko\b\s*([\s\S]*?)\s*--\>/g;return{qa:{},Qb:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.O.dc(b,c)},d)},dc:function(a,f){return a.replace(c,function(a,c,d,e,h,i,u){return b(u,c,f)}).replace(d,function(a,c){return b(c,"<\!-- ko --\>",f)})},Bb:function(b){return a.W.Aa(function(c,d){c.nextSibling&&a.Oa(c.nextSibling,b,d)})}}}();a.b("bindingRewriteValidators",a.O.qa);a.b("__tr_ambtns",a.O.Bb);(function(){a.l={};a.l.g=function(a){this.g=a};a.l.g.prototype.text=
function(){var b=a.a.p(this.g),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.g[b];var c=arguments[0];"innerHTML"===b?a.a.ha(this.g,c):this.g[b]=c};a.l.g.prototype.data=function(b){if(1===arguments.length)return a.s(this.g,"templateSourceData_"+b);a.n(this.g,"templateSourceData_"+b,arguments[1])};a.l.Q=function(a){this.g=a};a.l.Q.prototype=new a.l.g;a.l.Q.prototype.text=function(){if(0==arguments.length){var b=a.s(this.g,"__ko_anon_template__")||{};b.Ja===
n&&b.ta&&(b.Ja=b.ta.innerHTML);return b.Ja}a.n(this.g,"__ko_anon_template__",{Ja:arguments[0]})};a.l.g.prototype.nodes=function(){if(0==arguments.length)return(a.s(this.g,"__ko_anon_template__")||{}).ta;a.n(this.g,"__ko_anon_template__",{ta:arguments[0]})};a.b("templateSources",a.l);a.b("templateSources.domElement",a.l.g);a.b("templateSources.anonymousTemplate",a.l.Q)})();(function(){function b(b,c,d){for(var e,c=a.f.nextSibling(c);b&&(e=b)!==c;)b=a.f.nextSibling(e),(1===e.nodeType||8===e.nodeType)&&
d(e)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1];b(e,f,function(b){a.Na(d,b)});b(e,f,function(b){a.W.yb(b,[d])})}}function d(b,d,f,j,h){var h=h||{},i=b&&(b.nodeType?b:0<b.length?b[0]:p),i=i&&i.ownerDocument,u=h.templateEngine||e;a.O.Qb(f,u,i);f=u.renderTemplate(f,j,h,i);("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)&&o("Template engine must return an array of DOM nodes");i=r;switch(d){case "replaceChildren":a.f.N(b,f);i=m;break;case "replaceNode":a.a.qb(b,f);i=
m;break;case "ignoreTargetNode":break;default:o("Unknown renderMode: "+d)}i&&(c(f,j),h.afterRender&&h.afterRender(f,j.$data));return f}var e;a.Ga=function(b){b!=n&&!(b instanceof a.Z)&&o("templateEngine must inherit from ko.templateEngine");e=b};a.Ea=function(b,c,f,j,h){f=f||{};(f.templateEngine||e)==n&&o("Set a template engine before calling renderTemplate");h=h||"replaceChildren";if(j){var i=a.a.D(function(){var e=c&&c instanceof a.F?c:new a.F(a.a.d(c)),n="function"==typeof b?b(e.$data):b,e=d(j,
h,n,e,f);"replaceNode"==h&&(j=e,i&&i.Fa(j))});i&&i.$(j);return i}return a.W.Aa(function(d){a.Ea(b,c,f,d,"replaceNode")})};a.kc=function(b,e,f,j,h){function i(a,b){c(b,o);f.afterRender&&f.afterRender(b,a)}function u(a,c){var e="function"==typeof b?b(a):b;o=h.createChildContext(a);o.$index=c;return d(p,"ignoreTargetNode",e,o,f)}var o;return a.a.D(function(){var b=a.a.d(e)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.pa(b,function(b){return f.includeDestroyed||b===n||b===p||!a.a.d(b._destroy)});a.a.sb(j,
b,u,f,i)},j)};var f=a.a.z.M();a.c.template={flags:88,init:function(b,c){var d=a.a.d(c());if("string"!=typeof d&&!d.name&&(1==b.nodeType||8==b.nodeType))if(d=new a.l.Q(b),!d.nodes()){var e=a.f.childNodes(b),e=a.a.kb(e);d.nodes(e)}},update:function(b,c,d,e,h){var d=a.a.d(c()),i=m;"string"==typeof d?d={name:d}:("if"in d&&(i=i&&a.a.d(d["if"])),"ifnot"in d&&(i=i&&!a.a.d(d.ifnot)));e=d.name||b;c=p;"foreach"in d?c=a.kc(e,i&&d.foreach||[],d,b,h):i?(h="data"in d?h.createChildContext(d.data):h,c=a.Ea(e,h,d,
b)):a.f.da(b);h=c;(d=a.s(b,f))&&"function"==typeof d.m&&d.m();a.n(b,f,h);return c}};a.O.qa.template=function(b){b=a.w.nb(b);return 1==b.length&&b[0].unknown||a.w.ac(b,"name")?p:"This template engine does not support anonymous templates nested within its templates"}})();a.b("setTemplateEngine",a.Ga);a.b("renderTemplate",a.Ea);a.a.Ua=function(){function a(b,d,e,f){var g=Math.min,k=Math.max,l=[],j,h=b.length,i,n=d.length,o=n-h||1,q=h+n+1,s,t,x;for(j=0;j<=h;j++){t=s;l.push(s=[]);x=g(n,j+o);for(i=k(0,
j-1);i<=x;i++)s[i]=i?j?b[j-1]===d[i-1]?t[i-1]:g(t[i]||q,s[i-1]||q)+1:i+1:j+1}g=[];k=[];o=[];j=h;for(i=n;j||i;)h=l[j][i]-1,i&&h===l[j][i-1]?k.push(g[g.length]={status:e,value:d[--i],idx:i}):j&&h===l[j-1][i]?o.push(g[g.length]={status:f,value:b[--j],idx:j}):(g.push({status:"retained",value:d[--i]}),--j);if(k.length&&o.length)for(b=0;e=k[b];b++)for(d=0;f=o[d];d++)if(e.value===f.value){e.moved=f.idx;f.moved=e.idx;o.splice(d,1);break}return g.reverse()}return function(c,d){c=c||[];d=d||[];return c.length<=
d.length?a(c,d,"added","deleted"):a(d,c,"deleted","added")}}();a.b("utils.compareArrays",a.a.Ua);(function(){function b(b){for(;b.length&&!a.a.Ya(b[0]);)b.splice(0,1);if(1<b.length){for(var c=b[0],d=b[b.length-1],e=[c];c!==d;){c=c.nextSibling;if(!c)return;e.push(c)}Array.prototype.splice.apply(b,[0,b.length].concat(e))}return b}function c(a,c,d,e){e&&e.$(b(c))}function d(a){return a?function(b,d,e,f){a(b,d,e);c(0,d,0,f)}:c}function e(c,d,e,f){var h,i=a.a.D(function(){var n=c(d,f)||[];h?(i.Fa(),a.a.qb(b(h),
n),e(d,n,f,i),h.splice(0,h.length),a.a.R(h,n)):h=n});return{bc:h,i:i}}var f=a.a.z.M();a.a.sb=function(c,k,l,j,h){for(var k=k||[],j=j||{},h=d(h),i=a.s(c,f)===n,o=a.s(c,f)||[],q=a.a.ba(o,function(a){return a.Cb}),s=a.a.Ua(q,k),k=[],x=0,t=[],B=0,q=[],C=p,v=0,H;H=s[v];v++)switch(H.status){case "retained":var A=o[x++];A.gb(B++);k.push(A);0<A.U.length&&(C=A.U[A.U.length-1]);break;case "deleted":if(H.moved===n){var I=o[x];I.i&&I.i.m();a.a.e(b(I.U),function(a){t.push({P:a,na:v,oa:H.value});C=a})}++x;break;
case "added":var F,E,D;if(H.moved!==n)A=o[H.moved],A.gb(B++),F=b(A.U),E=m,k.push(A);else{var z=a.k(B++),I=e(l,D=H.value,h,z);F=I.bc;E=r;k.push({Cb:D,U:F,i:I.i,gb:z})}for(var A=0,M=F.length;A<M;A++){var K=F[A];E||q.push({P:K,na:v,oa:D});C==p?a.f.pb(c,K):a.f.hb(c,K,C);C=K}E||h(D,F,z,I.i)}a.a.e(t,function(b){a.ca(b.P)});l=r;if(!i){if(j.afterAdd)for(v=0;v<q.length;v++)j.afterAdd(q[v].P,q[v].na,q[v].oa);if(j.beforeRemove){for(v=0;v<t.length;v++)j.beforeRemove(t[v].P,t[v].na,t[v].oa);l=m}}if(!l&&t.length)for(v=
0;v<t.length;v++)j=t[v].P,j.parentNode&&j.parentNode.removeChild(j);a.n(c,f,k)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.sb);a.L=function(){this.allowTemplateRewriting=r};a.L.prototype=a.a.j(new a.Z,{renderTemplateSource:function(b){var c=!(9>a.a.ea)&&b.nodes?b.nodes():p;if(c)return a.a.H(c.cloneNode(m).childNodes);b=b.text();return a.a.Da(b)}});a.L.ib=new a.L;a.Ga(a.L.ib);a.b("nativeTemplateEngine",a.L);(function(){a.za=function(){var a=this.$b=function(){if("undefined"==typeof s||
!s.tmpl)return 0;try{if(0<=s.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f){f=f||{};2>a&&o("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var g=b.data("precompiled");g||(g=b.text()||"",g=s.template(p,"{{ko_with $item.koBindingContext}}"+g+"{{/ko_with}}"),b.data("precompiled",g));b=[e.$data];e=s.extend({koBindingContext:e},f.templateOptions);e=s.tmpl(g,b,e);e.appendTo(q.createElement("div"));
s.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){q.write("<script type='text/html' id='"+a+"'>"+b+"<\/script>")};0<a&&(s.tmpl.tag.ko_code={open:"__.push($1 || '');"},s.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.za.prototype=new a.Z;var b=new a.za;0<b.$b&&a.Ga(b);a.b("jqueryTmplTemplateEngine",a.za)})()})})(window,document,navigator,window.jQuery);
})();
